### ISSUE TITLE
Good submission, need some extra info on setting up Prometheus

### ISSUE THREAD

**Issue by JB273** [antonyip/Harmony_Prometheus-Grafana-Setup#2]
Hey Antony,

Nice submission, a couple of things though... Leo already mentioned how most validators run their nodes....

It looks like the information part on the prometheus is not enough to get it installed on Ubuntu... Can you take a look at this, we like this to be run as a service, just like you did on the Grafana part.

Other question, what is your setup for running this config (I assume Ubuntu Desktop? version?)

Keep up the good work!

**Comment by antonyip** [comment]
I don’t have a vps to test with. Also can i get a link to the guide that validators follow to host on vps? Maybe i can refer to that to write up a guide.

Promethus. Not sure what i’m missing? The tar xvf stuffs maybe?  Please let me know in more detail.

Im working on ubuntu desktop 18.04.

Regards,
Anton

On 9 Apr 2021, at 4:02 AM, JB273 ***@***.***> wrote:

﻿

Hey Antony,

Nice submission, a couple of things though... Leo already mentioned how most validators run their nodes....

It looks like the information part on the prometheus is not enough to get it installed on Ubuntu... Can you take a look at this

Other question, what is your setup for running this config (I assume Ubuntu Desktop? version?)

Keep up the good work!

**Comment by antonyip** [comment]
@JB273 Hi! Would be nice if you didn't edit your original message. I don't get an update from edits. :)

Updated the documented to have Prometheus as a service.

**Comment by JB273** [comment]
> @JB273 Hi! Would be nice if you didn't edit your original message. I don't get an update from edits. :)
> 
> Updated the documented to have Prometheus as a service.

Ah, sorry about that @antonyip that's me not using Github that much...
But yes it was about installing Prometheus as a service also.

**Comment by JB273** [comment]
> I don’t have a vps to test with. Also can i get a link to the guide that validators follow to host on vps? Maybe i can refer to that to write up a guide.

Hey @antonyip, there are many ways to get some free credit at Vultr or Digital Ocean for example...
And https://docs.harmony.one/home/network/validators is a good way to get familiar with the node setup, also testnet is covered here, if you run your validator there let me know I might be of help to you...

**Comment by antonyip** [comment]
Hi @JB273, I added a small section about Exposing port 9900 in the VPS. The steps afterwards are the same so I didn't see the need to make any new changes since the steps would work for installing it on the same VPS or a different one.

**Comment by JB273** [comment]
Hi @antonyip, do you think it is possible to make this more secure? 
Do we really need to open port 9900 to scrape the Prometheus metrics?
Or will this also work if we leave it just local?

Please let me know if you have other questions about this.

**Comment by antonyip** [comment]
Prom works by scraping the website at 9900. If the port is not open on the vps, you would not be able to access the webpage. If prom was installed locally on the vps, then you don’t have to open port 9900.

**Comment by JB273** [comment]
Okay, fair enough.. I'll close this one!
Good job!
